version: '3.8'
services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/logs:/app/logs

  ui:
    build: ./ui
    ports:
      - "3000:3000"

  job-manager:
    build: ./job-manager
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

